### ISSUE TITLE
Protoc installation fails because of AutoHotkey error

### ISSUE THREAD

**Issue by laribA** [VolantisDev/Launchpad#343]
**Describe the bug**
Protoc installation fails because of AutoHotkey error:

Error:   Failed
	Line#
-->	6356: Download(this.GetDownloadUrl(), destPath)

The current thread will exit.

**To Reproduce**
1. Install Launchpad
2. Launch Launchpad

**Expected behavior**
Dependency installer finishes as normal

**Screenshots**
![image](https://user-images.githubusercontent.com/64703812/141690810-60508388-19c5-4478-837a-e0108b9bc4f2.png)
![image](https://user-images.githubusercontent.com/64703812/141690824-d7b83b20-7596-4a9d-bcdc-22f94267e0ac.png)

**Required Details**
 - OS: Windows 10 64-bit
 - Launchpad Version 9.4.0

**Comment by bmcclure** [comment]
Thanks for the report! I wonder what is causing the download to fail. I will see if I can reproduce this somehow on my end, or at the very least see if I can get some better exception handling in place for failed downloads so we can get a more helpful error.

**Comment by laribA** [comment]
You're welcome! I just wanted to add: I tried manually downloading the 64-bit version of protoc 3.14.0 and putting it in the ./Vendor/Protoc folder, but it didn't do anything.

**Comment by laribA** [comment]
I launched Launchpad as administrator (which I tried before), and for some reason, it worked. My system really is an enigma.
